apiVersion: v1
kind: Service
metadata:
  name: gdm-server
spec:
  selector:
    name: gdm-server
  clusterIP: None
  ports:
  - name: gdmport # name is not required for single-port Services
    port: 50051
---
apiVersion: v1
kind: Pod
metadata:
  name: gdm-server
  labels:
    name: gdm-server
spec:
  containers:
  - name: gdm-server
    image: us-central1-docker.pkg.dev/group8-391123/gdm/server
    imagePullPolicy: Always
    command: ["python3"]
    args: ["gdm_server.py", "--mongo_url", "mongodb://mongo:27017/"] 
    ports:
    - containerPort: 50051
    resources:
      requests:
        memory: "50Mi"
        cpu: "20m"
      limits:
        memory: "250Mi"
        cpu: "200m"
